### ISSUE TITLE
Batch launch raises a "what" exception

### ISSUE THREAD

**Issue by ttben** [Pataclop/Movinyl#10]
After running script 0, 1 and 2, the `3_BATCH_LAUNCH` raises the following exception at the very end of the procedure (2000 over 2006):

```
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.2.0) ../modules/imgproc/src/resize.cpp:4045: error: (-215:Assertion failed) !ssize.empty() in function 'resize'
```

Maybe [this is ](https://stackoverflow.com/a/39405992/5259677) a starting point: 

-- **EDIT**-- 
Surrounding the resize call in `disk.cpp` obviously silence the error,  but also outputs the image.

```
try {
		resize(img, tmp, Size((2*FrameNumber)-2*i, (2*FrameNumber)-2*i),INTER_NEAREST);
} catch (const std::exception& e) { /* */ }
```

**Comment by Pataclop** [comment]
I had this error once but it only happened with a particular movie file, I guessed there was a problem with the movie... Thanks for the fix !

**Comment by ttben** [comment]
This is actually not a fix
Do you have any information on the movie that triggered the issue on your side?
Maybe we share some commonalities...

Or, it is expected to have the last image "null" thus yielding the exception?

**Comment by Pataclop** [comment]
Ok I fixed it the hard way, apparently it tried to open the n+1 image (that doesn't exist). Now the limit is hard coded in the 3_BATCH_LAUNCH file (2000 images by default)
