### ISSUE TITLE
[docker] colorpicker module

### ISSUE THREAD

**Issue by shiioo** [Pataclop/Movinyl#18]
After successfully building a docker, I'm greeted with this issue upon launching it:

```
Traceback (most recent call last):
  File "/app/movinyl.py", line 14, in <module>
    from color_picker import get_points, kmeans
ModuleNotFoundError: No module named 'color_picker'
```

Can't seem to find the proper module to add to the requirements.
Running under Ubuntu 20 through WSL 2.

Not happening with the non-docker version.

**Comment by Pataclop** [comment]
Sorry, there are no plans to update the docker version (I'm not very docker proficient...) 
The non docker version is supposed to be far simpler to use now
